Revert "close the script engine's class loader to close any files that were opened by it"
URLClassLoader.close() is only available in JDK 7 or later and the fix
causes NoClassDefFoundErrors when processing multiple scripts.

This reverts commit 871cbee4fc5f117fc6e1bfb4252aee9e3c8e2915.