Replace - with _ in groovy filenames
The "-" is not accepted in the name of scripts and may lead
to the following error:

  ERROR: invalid script name 'foo-bar.groovy; script names
  may only contain letters, digits and underscores, but
  may not start with a digit

It is quite frustrating to have an example from the
documentation which does not work. Hence, the change
for a valid character: "_".